<?php
/**
 * Created by PhpStorm.
 * User: xx
 * Date: 2019-2-14
 * Time: 22:17
 */
namespace app\lib\exception;

use think\exception\Handle;
use think\Request;

class ExceptionHandler extends Handle {
    private $code;
    private $msg;
    private $errorCode;
    //需要返回客户端请求的url
    public function render(\Exception $e)
    {
        if($e instanceof BaseException){
            //自定义异常
            $this->code = $e->code;
            $this->msg = $e->msg;
            $this->errorCode = $e->errorCode;
        }else{
            if (config('app_debug')){
                //return default error page
                return parent::render($e);
            }else{
                $this->code =500;
                $this->msg ='服务器内部错误';
                $this->errorCode = 999;
            }
        }
        $request = Request::instance();

        $result = [
            'msg' =>$this->msg,
            'error_code' => $this->errorCode,
            'request_url' => $request->url()
        ];
        return json($result,$this->code); // TODO: Change the autogenerated stub
    }
}